package com.example.hamsterone.utils

import com.example.hamsterone.models.Actor
import com.example.hamsterone.models.Gallery

object Consts {

    const val URL_BASE = ""
    const val URL_VIDEO_NEWEST = "https://xhamster.one"
    const val URL_VIDEO_BEST = "https://xhamster.one/best/weekly"
    const val URL_VIDEO_POPULAR = "https://xhamster.one/most-viewed/weekly"
    const val URL_ACTOR_PORNSTAR = "https://xhamster.one/pornstars"
    const val URL_ACTOR_CELEBRITIES = "https://xhamster.one/celebrities"
    const val URL_ACTOR_AMATEUR = "https://xhamster.one/amateurs"
    var NULL_ACTOR = Actor(0, "null_actor", "", "", "", "", false)
    const val URL_PHOTO = "https://xhamster.one/photos"
    var NULL_GALLERY = Gallery(0, "null_gallery", "", "", "", "", false)

    val CATEGORY_TITLES = arrayOf(
        "Amateur",
        "Anal Beads",
        "Anal Fisting",
        "Anal Gape",
        "Anal Masturbation",
        "Anal Sex",
        "Anal Toys",
        "Anime",
        "Arab",
        "Asian",
        "Ass to Mouth",
        "Babysitter",
        "BBW",
        "Beach",
        "Bi-Sexual",
        "Big Ass",
        "Big Cocks",
        "Big Tits",
        "Black",
        "Blonde",
        "Blowjob",
        "Bondage",
        "Brazilian",
        "British",
        "Brunette",
        "Bukkake",
        "Butt Plug",
        "Camel Toe",
        "Celebrity",
        "CFNM",
        "Chubby",
        "College",
        "Compilation",
        "Cougar",
        "Couples",
        "Creampie",
        "Cum in Mouth",
        "Cum on Face",
        "Cum Swap",
        "Cumshot",
        "Dildo",
        "Doggy Style",
        "Double Blowjob",
        "Double Ended Dildo",
        "Double Penetration",
        "Face Sitting",
        "Family Roleplay",
        "FFM",
        "Fishnet Stockings",
        "Food",
        "Footjob",
        "French",
        "Gag",
        "Gangbang",
        "Gay",
        "German",
        "Glory Hole",
        "Granny",
        "Group Sex",
        "Hairy Pussy",
        "Handcuffs",
        "Handjob",
        "Hardcore",
        "HD Porn",
        "Homemade",
        "Indian",
        "Interracial",
        "Italian",
        "Japanese",
        "Kissing",
        "Korean",
        "Lactating",
        "Latex",
        "Latina",
        "Lesbian",
        "Lesbian Scissoring",
        "Licking",
        "Massage",
        "Masturbation",
        "Mature",
        "Midget",
        "MILF",
        "Nurse",
        "Oil/Lotion",
        "Party",
        "Police",
        "POV",
        "Pregnant",
        "Public Flashing",
        "Pussy Fisting",
        "Redhead",
        "Reverse Cowgirl",
        "Russian",
        "Sex Machine",
        "Sex Toys",
        "Shaved Pussy",
        "Shaving",
        "Sixty-Nine",
        "Small Dick",
        "Small Tits",
        "Smoking",
        "Solo",
        "SpanKing",
        "Spread Pussy",
        "Spreadeagle",
        "Squirting",
        "Strap On",
        "Swedish",
        "Teen",
        "Thai",
        "Threesomes",
        "Throat Fuck",
        "Titty Fuck",
        "Transgender",
        "Turkish",
        "Upskirt",
        "Vintage",
        "Voyeur",
        "VR Porn",
        "Webcam"
    )
    val CATEGORY_THUMBS = arrayOf(
        "https://mediav.porn.com/images/cats/9.jpg",
        "https://mediav.porn.com/images/cats/220.jpg",
        "https://mediav.porn.com/images/cats/195.jpg",
        "https://mediav.porn.com/images/cats/251.jpg",
        "https://mediav.porn.com/images/cats/220.jpg",
        "https://mediav.porn.com/images/cats/29.jpg",
        "https://mediav.porn.com/images/cats/41.jpg",
        "https://mediav.porn.com/images/cats/158.jpg",
        "https://mediav.porn.com/images/cats/280.jpg",
        "https://mediav.porn.com/images/cats/166.jpg",
        "https://mediav.porn.com/images/cats/63.jpg",
        "https://mediav.porn.com/images/cats/353.jpg",
        "https://mediav.porn.com/images/cats/182.jpg",
        "https://mediav.porn.com/images/cats/79.jpg",
        "https://mediav.porn.com/images/cats/4.jpg",
        "https://mediav.porn.com/images/cats/309.jpg",
        "https://mediav.porn.com/images/cats/171.jpg",
        "https://mediav.porn.com/images/cats/172.jpg",
        "https://mediav.porn.com/images/cats/170.jpg",
        "https://mediav.porn.com/images/cats/175.jpg",
        "https://mediav.porn.com/images/cats/26.jpg",
        "https://mediav.porn.com/images/cats/65.jpg",
        "https://mediav.porn.com/images/cats/357.jpg",
        "https://mediav.porn.com/images/cats/276.jpg",
        "https://mediav.porn.com/images/cats/176.jpg",
        "https://mediav.porn.com/images/cats/392.jpg",
        "https://mediav.porn.com/images/cats/221.jpg",
        "https://mediav.porn.com/images/cats/75.jpg",
        "https://mediav.porn.com/images/cats/351.jpg",
        "https://mediav.porn.com/images/cats/355.jpg",
        "https://mediav.porn.com/images/cats/341.jpg",
        "https://mediav.porn.com/images/cats/306.jpg",
        "https://mediav.porn.com/images/cats/253.jpg",
        "https://mediav.porn.com/images/cats/187.jpg",
        "https://mediav.porn.com/images/cats/265.jpg",
        "https://mediav.porn.com/images/cats/50.jpg",
        "https://mediav.porn.com/images/cats/52.jpg",
        "https://mediav.porn.com/images/cats/51.jpg",
        "https://mediav.porn.com/images/cats/157.jpg",
        "https://mediav.porn.com/images/cats/298.jpg",
        "https://mediav.porn.com/images/cats/217.jpg",
        "https://mediav.porn.com/images/cats/365.jpg",
        "https://mediav.porn.com/images/cats/201.jpg",
        "https://mediav.porn.com/images/cats/219.jpg",
        "https://mediav.porn.com/images/cats/302.jpg",
        "https://mediav.porn.com/images/cats/190.jpg",
        "https://mediav.porn.com/images/cats/314.jpg",
        "https://mediav.porn.com/images/cats/321.jpg",
        "https://mediav.porn.com/images/cats/125.jpg",
        "https://mediav.porn.com/images/cats/71.jpg",
        "https://mediav.porn.com/images/cats/27.jpg",
        "https://mediav.porn.com/images/cats/361.jpg",
        "https://mediav.porn.com/images/cats/269.jpg",
        "https://mediav.porn.com/images/cats/162.jpg",
        "https://mediav.porn.com/images/cats/2.jpg",
        "https://mediav.porn.com/images/cats/281.jpg",
        "https://mediav.porn.com/images/cats/74.jpg",
        "https://mediav.porn.com/images/cats/184.jpg",
        "https://mediav.porn.com/images/cats/164.jpg",
        "https://mediav.porn.com/images/cats/267.jpg",
        "https://mediav.porn.com/images/cats/238.jpg",
        "https://mediav.porn.com/images/cats/25.jpg",
        "https://mediav.porn.com/images/cats/28.jpg",
        "https://mediav.porn.com/images/cats/300.jpg",
        "https://mediav.porn.com/images/cats/8.jpg",
        "https://mediav.porn.com/images/cats/169.jpg",
        "https://mediav.porn.com/images/cats/183.jpg",
        "https://mediav.porn.com/images/cats/282.jpg",
        "https://mediav.porn.com/images/cats/359.jpg",
        "https://mediav.porn.com/images/cats/24.jpg",
        "https://mediav.porn.com/images/cats/277.jpg",
        "https://mediav.porn.com/images/cats/194.jpg",
        "https://mediav.porn.com/images/cats/134.jpg",
        "https://mediav.porn.com/images/cats/167.jpg",
        "https://mediav.porn.com/images/cats/3.jpg",
        "https://mediav.porn.com/images/cats/191.jpg",
        "https://mediav.porn.com/images/cats/305.jpg",
        "https://mediav.porn.com/images/cats/69.jpg",
        "https://mediav.porn.com/images/cats/304.jpg",
        "https://mediav.porn.com/images/cats/308.jpg",
        "https://mediav.porn.com/images/cats/196.jpg",
        "https://mediav.porn.com/images/cats/186.jpg",
        "https://mediav.porn.com/images/cats/142.jpg",
        "https://mediav.porn.com/images/cats/215.jpg",
        "https://mediav.porn.com/images/cats/252.jpg",
        "https://mediav.porn.com/images/cats/145.jpg",
        "https://mediav.porn.com/images/cats/13.jpg",
        "https://mediav.porn.com/images/cats/70.jpg",
        "https://mediav.porn.com/images/cats/193.jpg",
        "https://mediav.porn.com/images/cats/62.jpg",
        "https://mediav.porn.com/images/cats/177.jpg",
        "https://mediav.porn.com/images/cats/373.jpg",
        "https://mediav.porn.com/images/cats/283.jpg",
        "https://mediav.porn.com/images/cats/223.jpg",
        "https://mediav.porn.com/images/cats/299.jpg",
        "https://mediav.porn.com/images/cats/266.jpg",
        "https://mediav.porn.com/images/cats/68.jpg",
        "https://mediav.porn.com/images/cats/189.jpg",
        "https://mediav.porn.com/images/cats/255.jpg",
        "https://mediav.porn.com/images/cats/254.jpg",
        "https://mediav.porn.com/images/cats/67.jpg",
        "https://mediav.porn.com/images/cats/264.jpg",
        "https://mediav.porn.com/images/cats/64.jpg",
        "https://mediav.porn.com/images/cats/59.jpg",
        "https://mediav.porn.com/images/cats/377.jpg",
        "https://mediav.porn.com/images/cats/60.jpg",
        "https://mediav.porn.com/images/cats/202.jpg",
        "https://mediav.porn.com/images/cats/284.jpg",
        "https://mediav.porn.com/images/cats/185.jpg",
        "https://mediav.porn.com/images/cats/278.jpg",
        "https://mediav.porn.com/images/cats/163.jpg",
        "https://www.porn.com/videos/throat-fuck",
        "https://mediav.porn.com/images/cats/30.jpg",
        "https://mediav.porn.com/images/cats/161.jpg",
        "https://mediav.porn.com/images/cats/279.jpg",
        "https://mediav.porn.com/images/cats/192.jpg",
        "https://mediav.porn.com/images/cats/19.jpg",
        "https://mediav.porn.com/images/cats/10.jpg",
        "https://mediav.porn.com/images/cats/390.jpg",
        "https://mediav.porn.com/images/cats/385.jpg"
    )


}